const tubewells = {
  type: "FeatureCollection",
  name: "tubewells",
  crs: { type: "name", properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  features: [
    {
      type: "Feature",
      properties: {
        OBJECTID: 1,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "1",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.957392273373486, 31.603766758389416, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 2,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "2",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.953723303407727, 31.604236219660965, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 3,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "3",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.951455809022249, 31.607599074798628, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 4,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "4",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.948146281391502, 31.609747148975504, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 5,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "5",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.944065307365989, 31.609488918355964, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 6,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "6",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.940222048392414, 31.608484262924666, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 7,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "7",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.935997532759146, 31.608781195222843, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 8,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "8",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931341189653651, 31.60956114564992, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 9,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "9",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.926991188651499, 31.609322505327842, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 10,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "10",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.923262728501271, 31.608003385228642, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 11,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "11",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.919335359861705, 31.606308724154008, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 12,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "12",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931003187906057, 31.612762503097134, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 13,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "13",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.930955862607135, 31.616428129959292, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 14,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "14",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931277709703949, 31.620181139414274, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 15,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "15",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931492461382106, 31.623677673185483, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 16,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "16",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931621173990166, 31.627322797681714, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 17,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "17",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931685311377692, 31.631110955388099, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 18,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "18",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.931194055725683, 31.633528791019099, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 19,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "19",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.930537720075975, 31.637797237359898, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 20,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "20",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.930000679618232, 31.640910104258175, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 21,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "21",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.929415962671982, 31.643910100841783, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 22,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "22",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.929579197489517, 31.647499635254185, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 23,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "23",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.929733653699358, 31.651167462662954, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 24,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "125 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "24",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.929825099377823, 31.65473339816279, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 25,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1988",
        Name: "25",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.959802931428641, 31.605016086937738, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 26,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1997",
        Name: "26",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.964846439740271, 31.605332051793205, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 27,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1997",
        Name: "27",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.969711385646235, 31.603109915161561, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 28,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1997",
        Name: "28",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.974121934934715, 31.603066238804427, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 29,
        Id: 0,
        Capacity: "4 Cusec",
        Made: "Siemens",
        MotorPower: "100 HP",
        Area_Serve: "TUBE WELLS AT CHENAB WELL FIELD AREA, CHINIOT",
        Status: "OPERATIONAL",
        Age: "1997",
        Name: "29",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.976442928475549, 31.605188057507565, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 98,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "12",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.025788462169899, 31.578624493611684, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 99,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "11",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.031296428543271, 31.581115053069027, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 100,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "10",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.037392454516237, 31.583989346370679, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 101,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "9",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.042883215235662, 31.586557547402236, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 102,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "8",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.048267590822604, 31.589801212002147, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 103,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "7",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.052721250227549, 31.59394104455183, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 104,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "6",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.055962898795187, 31.598695266095611, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 105,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "5",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.058946380696696, 31.603352087299562, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 106,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "4",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.061792896837474, 31.608496262717289, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 107,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "13",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.022919354771375, 31.577253881343712, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 108,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "14",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.014472060793949, 31.573339566447462, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 109,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "15",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.009046187492515, 31.570785829797309, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 110,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "18",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.992202499998044, 31.563628644104785, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 111,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "19",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.986099308357296, 31.560472438494294, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 112,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "17",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.998264501951198, 31.565769646700346, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 113,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "16",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.003490593272616, 31.568209455596417, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 114,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "3",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.064805415872542, 31.613380577552611, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 115,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "2",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.067101323055439, 31.617728831977207, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 116,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "1",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.070154931474633, 31.623242274766135, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 117,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "20",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.979967066949854, 31.560259306044234, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 118,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "21",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.973423824253828, 31.558420614298388, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 119,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "22",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.967509659169266, 31.556740634479095, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 120,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "23",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.96090454243155, 31.554816984897943, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 121,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "24",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.955185594623444, 31.553199678039526, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 122,
        Id: 0,
        Capacity: "2 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELLS ALONG JHANG BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2011",
        Name: "25",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [72.948647858620077, 31.550920014626872, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 32,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: "25 H.P",
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "1985",
        Name: "4",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.120847029393758, 31.429817694436768, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 33,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: "25 H.P",
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2000",
        Name: "3",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.120107019198215, 31.42921264971292, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 34,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: "25 H.P",
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "1985",
        Name: "2",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.119291694120236, 31.428606565514482, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 43,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "1992",
        Name: "7",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.147408391921616, 31.449450023450133, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 77,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "1992",
        Name: "8",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.15689326582698, 31.453279954106556, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 80,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "1992",
        Name: "9",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.159253214396273, 31.454167927874117, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 4,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2002",
        Name: "Mansoorabad-1",
        Repl_Y: "25",
        Condition: "NON-OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.124087076477764, 31.432686924866616, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 6,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2002",
        Name: "3",
        Repl_Y: "25",
        Condition: "NON-OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.133209217277027, 31.439349860498059, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 7,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2002",
        Name: "4",
        Repl_Y: "25",
        Condition: "OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.134698446332052, 31.440483984024116, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 8,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: "OPERATIONAL",
        Age: "2002",
        Name: "5",
        Repl_Y: "25",
        Condition: "NON-OPERATIONAL",
      },
      geometry: {
        type: "Point",
        coordinates: [73.140047918946891, 31.444566712554153, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: "1 Cusec",
        Made: null,
        MotorPower: null,
        Area_Serve: "TUBE WELL ALONG RAKH BRANCH CANAL",
        Status: null,
        Age: "2015",
        Name: "Madina Town TW 1",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.117673453251399, 31.427475062243367, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "NON-OPERATIONAL",
        Age: null,
        Name: "MALAKPUR",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.15181982667545, 31.452279779018546, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "MANANWALA 1",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.157021244788595, 31.454087468113141, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "MANANWALA 2",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.1580620241986, 31.454467604192441, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "GATWALA 1",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.163024775737782, 31.455535333779043, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "2",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.165804914209119, 31.456527471371469, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "3",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.168260891934082, 31.457369325682755, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "4",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.170665908392166, 31.458256945755117, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "5",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.174427252277724, 31.459557669533744, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "6",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.176196912360226, 31.46019149272335, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "7",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.178464751671044, 31.460981548064375, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "8",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.180371775669443, 31.461685289246823, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: "OPERATIONAL",
        Age: null,
        Name: "9",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.183037274301171, 31.462591896941717, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 1,
        Capacity: "1",
        Made: null,
        MotorPower: null,
        Area_Serve: "Changa Pani Sahmshabd",
        Status: null,
        Age: null,
        Name: null,
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.183174787628047, 31.463366205317151, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 2,
        Capacity: "1",
        Made: null,
        MotorPower: null,
        Area_Serve: "Changa Pani Sahmshabd",
        Status: null,
        Age: null,
        Name: null,
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.180350547903856, 31.462386032994161, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: "1",
        Made: null,
        MotorPower: null,
        Area_Serve: "10 Number Tw Farnch",
        Status: null,
        Age: null,
        Name: null,
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.186325732217441, 31.463887587159245, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: null,
        Age: null,
        Name: "49 JB",
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [72.987411788503564, 31.562299213094075, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 0,
        Id: 0,
        Capacity: null,
        Made: null,
        MotorPower: null,
        Area_Serve: null,
        Status: null,
        Age: null,
        Name: null,
        Repl_Y: null,
        Condition: null,
      },
      geometry: {
        type: "Point",
        coordinates: [73.125972327221973, 31.500333160927358, 0.0],
      },
    },
  ],
};
export default tubewells;
