const ohr = {
  type: "FeatureCollection",
  name: "ohr_4326",
  crs: { type: "name", properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  features: [
    {
      type: "Feature",
      properties: {
        OBJECTID: 1,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "40",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Abdullah Pur OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.10272622578178, 31.420870254639862, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 2,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "L=77 Feet, W=62 Feet",
        PUMPS: "2",
        PUMPS_SIZE: null,
        CONNECTION: "44",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Peoples Colony1 OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.1047780688112, 31.412295240998894, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 3,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Peoples Colony2 OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.113984425399281, 31.404975789717074, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 4,
        OHR_HEIGHT: "100 feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "67",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Peoples Colony 17w OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.110183504543869, 31.401082968588117, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 5,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "42 Feet",
        PUMPS: "3",
        PUMPS_SIZE: "2=2Cusec, 1=4Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Batala Colony OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.100232772624281, 31.398273671707695, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 6,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "42 Feet",
        PUMPS: "4",
        PUMPS_SIZE: "2=2Cusec, 2=1Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Waris Pura OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.098008672560312, 31.394053794033525, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 7,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "62 Feet",
        PUMPS: "6",
        PUMPS_SIZE: "3=2Cusec, 3=1Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "D-Type Colony OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.078171834933826, 31.381827329509886, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 8,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Saman Abad(QadriChowk)OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.070400920196775, 31.385835940452306, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 9,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "2",
        PUMPS_SIZE: "2Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Saman Abad OHR2",
      },
      geometry: {
        type: "Point",
        coordinates: [73.065611133304913, 31.385243018104113, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 10,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "4",
        PUMPS_SIZE: "2=3Cusec,2=2Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Head Water Works OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.091487834289708, 31.411297032521912, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 11,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "42 Feet",
        PUMPS: "2",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Factory Area OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.08337701008395, 31.408033115204411, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 12,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: "3",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: "51",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "212RB SirSyed Town OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.073717405457074, 31.401255989064296, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 13,
        OHR_HEIGHT: "74 Feet",
        OHR_DEPTH: "15 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: "32 Feet",
        PUMPS: "2",
        PUMPS_SIZE: "1Cusec",
        CONNECTION: "53",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Nazim Abad OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.069571355024905, 31.408690083190962, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 14,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "33",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Jhang Bazar OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.07348872186887, 31.414393926981774, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 15,
        OHR_HEIGHT: "50 Feet",
        OHR_DEPTH: "12 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "2",
        PUMPS_SIZE: "204 m^3/hour",
        CONNECTION: "31",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Karkhana Bazar OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.082223769004116, 31.416579288420944, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 16,
        OHR_HEIGHT: "64 Feet",
        OHR_DEPTH: "11 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "29",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Civil Lines OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.086622758225261, 31.425108043877149, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 17,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Not in te Govt of wasa",
        AGE: null,
        CONDITION: null,
        Name: "DHQ Hospital OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.095000263052242, 31.419821294597565, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 18,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "7",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gujjar Basti OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.072636625852269, 31.424391529287295, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 19,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "10",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Jinnah Colony OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.066613463697678, 31.420368443353876, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 20,
        OHR_HEIGHT: "75 Feet",
        OHR_DEPTH: "10 Feet",
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "8",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Dhobi Ghat OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.072697056266207, 31.419116116834282, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 21,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "9",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulberg OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.0616316217763, 31.421032844984829, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 22,
        OHR_HEIGHT: "80 Feet",
        OHR_DEPTH: "12 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Muhammad Pura OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.060860656081772, 31.42728326551596, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 23,
        OHR_HEIGHT: "66 Feet",
        OHR_DEPTH: "14 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "2 New, 1 Old",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "G.M Abad Adam Chowk OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.054627639189476, 31.437245030224787, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 24,
        OHR_HEIGHT: "75 Feet",
        OHR_DEPTH: "10 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Kanak Basti OHR GMA",
      },
      geometry: {
        type: "Point",
        coordinates: [73.064097332456569, 31.442026461216781, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 25,
        OHR_HEIGHT: "75 Feet",
        OHR_DEPTH: "10 Feet",
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: "27",
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Islam Nagar OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.089864720982149, 31.433544437993749, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 26,
        OHR_HEIGHT: "98 Feet",
        OHR_DEPTH: "10 Feet",
        DIAMETER_I: "L=86, W=86 (Feet)",
        DIAMETER_E: null,
        OHR_SHAPE: "Rectangular",
        VOLUME_cub: "2250",
        GROUND_TAN: null,
        PUMPS: "8",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: "80",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulistan2 OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.092187963935672, 31.445595357071291, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 27,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: "3",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulistan WW-G BLOCK GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.103369482759391, 31.444286327355403, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 28,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "2",
        PUMPS_SIZE: "1=1Cusec, 1=2Cusec",
        CONNECTION: "25",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulfishan Colony OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.041115316987202, 31.406876134115347, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 29,
        OHR_HEIGHT: "72 Feet",
        OHR_DEPTH: "12 Feet",
        DIAMETER_I: "42 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Rectangular",
        VOLUME_cub: "450",
        GROUND_TAN: "62 Feet",
        PUMPS: "6",
        PUMPS_SIZE: "3=2Cusec, 3=1Cusec",
        CONNECTION: "48",
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Allama iqbal OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.08043697730696, 31.385499619930208, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 30,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "675",
        GROUND_TAN: null,
        PUMPS: "4",
        PUMPS_SIZE: "2 Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "G.M Abad Water Works",
      },
      geometry: {
        type: "Point",
        coordinates: [73.056068090900098, 31.441081681430191, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 31,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Ahmad Nagar OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.095445730507862, 31.360597933333374, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 32,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulberg-C OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.059207057860164, 31.41940457599808, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 33,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Latif Chowk OHR GMA",
      },
      geometry: {
        type: "Point",
        coordinates: [73.043472178827912, 31.438193593394335, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 34,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Kaleem Shaheed Colony-2",
      },
      geometry: {
        type: "Point",
        coordinates: [73.027950804910631, 31.43548686964056, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 35,
        OHR_HEIGHT: "45 Feet",
        OHR_DEPTH: "5 Feet",
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "113",
        GROUND_TAN: null,
        PUMPS: "2",
        PUMPS_SIZE: "1Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Noor-ul-Amin Colony OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.103280466645302, 31.479083592640119, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 36,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Kaleem Shaheed Colony-1",
      },
      geometry: {
        type: "Point",
        coordinates: [73.039098806203569, 31.433058955003993, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 37,
        OHR_HEIGHT: "75 Feet",
        OHR_DEPTH: "9 Feet",
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: "Rectangular",
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: "3",
        PUMPS_SIZE: "2=2Cusec, 1=3Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative(in Progress)",
        AGE: null,
        CONDITION: null,
        Name: "Johar Colony",
      },
      geometry: {
        type: "Point",
        coordinates: [73.104812685152453, 31.457560943358324, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 38,
        OHR_HEIGHT: "60 Feet",
        OHR_DEPTH: "11 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "9",
        PUMPS_SIZE: "2Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Millat Town C Block",
      },
      geometry: {
        type: "Point",
        coordinates: [73.099877238358246, 31.488645404281794, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 39,
        OHR_HEIGHT: "60 Feet",
        OHR_DEPTH: "11 Feet",
        DIAMETER_I: "30.6 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: "Circular",
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: "9",
        PUMPS_SIZE: "2Cusec",
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Millat Town E Block",
      },
      geometry: {
        type: "Point",
        coordinates: [73.108978831325373, 31.492415173158971, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 40,
        OHR_HEIGHT: "65 Feet",
        OHR_DEPTH: "12 Feet",
        DIAMETER_I: "42 Feet",
        DIAMETER_E: "108 Feet",
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Madina Town OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.12507452143349, 31.423364535733768, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 41,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "CHAK NO 279/R.B OHR",
      },
      geometry: {
        type: "Point",
        coordinates: [73.033793900081861, 31.425305696440724, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 42,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "OHR Gokhuwal",
      },
      geometry: {
        type: "Point",
        coordinates: [73.086234167730936, 31.480895447941773, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 43,
        OHR_HEIGHT: "65 Feet",
        OHR_DEPTH: "12 Feet",
        DIAMETER_I: "42 Feet",
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: null,
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Non-Operative",
        AGE: null,
        CONDITION: null,
        Name: "Madina Town OHR No.1",
      },
      geometry: {
        type: "Point",
        coordinates: [73.119337474018025, 31.421986492299677, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 44,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulistan2 GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.092487589282271, 31.445855442443897, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 45,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "900",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Millat Town GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.108321997750693, 31.494978968437817, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 46,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "630",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Jahl Water Works GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.087987780564362, 31.408103255329159, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 47,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Gulfishan Colony GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.041168874169728, 31.4070918732554, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 48,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "44000",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "TR new GT 1",
      },
      geometry: {
        type: "Point",
        coordinates: [73.061424334534337, 31.48607292270945, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 49,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "20000",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "TR - old GT - tank 1",
      },
      geometry: {
        type: "Point",
        coordinates: [73.062068165469469, 31.485657880158666, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 50,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Batala Colony GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.100261004451511, 31.398251541927486, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 51,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Waris Pura GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.098117687518894, 31.394159330066898, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 52,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "900",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Allama iqbal WW GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.076351284655715, 31.392036008870825, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 53,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "225",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Nazim Abad GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.069521211775566, 31.408640367421548, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 54,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Factory Area GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.083330575581428, 31.407994306180054, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 55,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "450",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Karkhana Bazar GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.082375980758556, 31.41669328869391, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 56,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "135",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "Saman ABad GT",
      },
      geometry: {
        type: "Point",
        coordinates: [73.065518712671363, 31.385313720150673, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 57,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "20000",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "TR - old GT - tank 2",
      },
      geometry: {
        type: "Point",
        coordinates: [73.062396954936318, 31.485823787140781, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 58,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "44000",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "Operative",
        AGE: null,
        CONDITION: null,
        Name: "TR new GT 2",
      },
      geometry: {
        type: "Point",
        coordinates: [73.061578806106695, 31.485824513517745, 0.0],
      },
    },
    {
      type: "Feature",
      properties: {
        OBJECTID: 59,
        OHR_HEIGHT: null,
        OHR_DEPTH: null,
        DIAMETER_I: null,
        DIAMETER_E: null,
        OHR_SHAPE: null,
        VOLUME_cub: "0",
        GROUND_TAN: null,
        PUMPS: null,
        PUMPS_SIZE: null,
        CONNECTION: null,
        PROJECT: null,
        STATUS: "NEW",
        AGE: null,
        CONDITION: null,
        Name: "CHANGA PANI",
      },
      geometry: {
        type: "Point",
        coordinates: [73.130982613101324, 31.463261515892576, 0.0],
      },
    },
  ],
};
export default ohr;
